[project]
name = "jon-eoy-album-mosaic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "pillow>=12.1.0",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
